var data = {
  "nodes": [
    {
      "id": 0,
      "label": "Myriel"
    }, {
      "id": 1,
      "label": "Napoleon"
    }, {
      "id": 2,
      "label": "MlleBaptistine"
    }, {
      "id": 3,
      "label": "MmeMagloire"
    }, {
      "id": 4,
      "label": "CountessDeLo"
    }, {
      "id": 5,
      "label": "Geborand"
    }, {
      "id": 6,
      "label": "Champtercier"
    }, {
      "id": 7,
      "label": "Cravatte"
    }, {
      "id": 8,
      "label": "Count"
    }, {
      "id": 9,
      "label": "OldMan"
    }, {
      "id": 10,
      "label": "Labarre"
    }, {
      "id": 11,
      "label": "Valjean"
    }, {
      "id": 12,
      "label": "Marguerite"
    }, {
      "id": 13,
      "label": "MmeDeR"
    }, {
      "id": 14,
      "label": "Isabeau"
    }, {
      "id": 15,
      "label": "Gervais"
    }, {
      "id": 16,
      "label": "Tholomyes"
    }, {
      "id": 17,
      "label": "Listolier"
    }, {
      "id": 18,
      "label": "Fameuil"
    }, {
      "id": 19,
      "label": "Blacheville"
    }, {
      "id": 20,
      "label": "Favourite"
    }, {
      "id": 21,
      "label": "Dahlia"
    }, {
      "id": 22,
      "label": "Zephine"
    }, {
      "id": 23,
      "label": "Fantine"
    }, {
      "id": 24,
      "label": "MmeThenardier"
    }, {
      "id": 25,
      "label": "Thenardier"
    }, {
      "id": 26,
      "label": "Cosette"
    }, {
      "id": 27,
      "label": "Javert"
    }, {
      "id": 28,
      "label": "Fauchelevent"
    }, {
      "id": 29,
      "label": "Bamatabois"
    }, {
      "id": 30,
      "label": "Perpetue"
    }, {
      "id": 31,
      "label": "Simplice"
    }, {
      "id": 32,
      "label": "Scaufflaire"
    }, {
      "id": 33,
      "label": "Woman1"
    }, {
      "id": 34,
      "label": "Judge"
    }, {
      "id": 35,
      "label": "Champmathieu"
    }, {
      "id": 36,
      "label": "Brevet"
    }, {
      "id": 37,
      "label": "Chenildieu"
    }, {
      "id": 38,
      "label": "Cochepaille"
    }, {
      "id": 39,
      "label": "Pontmercy"
    }, {
      "id": 40,
      "label": "Boulatruelle"
    }, {
      "id": 41,
      "label": "Eponine"
    }, {
      "id": 42,
      "label": "Anzelma"
    }, {
      "id": 43,
      "label": "Woman2"
    }, {
      "id": 44,
      "label": "MotherInnocent"
    }, {
      "id": 45,
      "label": "Gribier"
    }, {
      "id": 46,
      "label": "Jondrette"
    }, {
      "id": 47,
      "label": "MmeBurgon"
    }, {
      "id": 48,
      "label": "Gavroche"
    }, {
      "id": 49,
      "label": "Gillenormand"
    }, {
      "id": 50,
      "label": "Magnon"
    }, {
      "id": 51,
      "label": "MlleGillenormand"
    }, {
      "id": 52,
      "label": "MmePontmercy"
    }, {
      "id": 53,
      "label": "MlleVaubois"
    }, {
      "id": 54,
      "label": "LtGillenormand"
    }, {
      "id": 55,
      "label": "Marius"
    }, {
      "id": 56,
      "label": "BaronessT"
    }, {
      "id": 57,
      "label": "Mabeuf"
    }, {
      "id": 58,
      "label": "Enjolras"
    }, {
      "id": 59,
      "label": "Combeferre"
    }, {
      "id": 60,
      "label": "Prouvaire"
    }, {
      "id": 61,
      "label": "Feuilly"
    }, {
      "id": 62,
      "label": "Courfeyrac"
    }, {
      "id": 63,
      "label": "Bahorel"
    }, {
      "id": 64,
      "label": "Bossuet"
    }, {
      "id": 65,
      "label": "Joly"
    }, {
      "id": 66,
      "label": "Grantaire"
    }, {
      "id": 67,
      "label": "MotherPlutarch"
    }, {
      "id": 68,
      "label": "Gueulemer"
    }, {
      "id": 69,
      "label": "Babet"
    }, {
      "id": 70,
      "label": "Claquesous"
    }, {
      "id": 71,
      "label": "Montparnasse"
    }, {
      "id": 72,
      "label": "Toussaint"
    }, {
      "id": 73,
      "label": "Child1"
    }, {
      "id": 74,
      "label": "Child2"
    }, {
      "id": 75,
      "label": "Brujon"
    }, {
      "id": 76,
      "label": "MmeHucheloup"
    }],
  "links": [{
    "source": 1,
    "target": 0,
    "value": 1
  }, {
      "source": 2,
      "target": 0,
      "value": 8
    }, {
      "source": 3,
      "target": 0,
      "value": 10
    }, {
      "source": 3,
      "target": 2,
      "value": 6
    }, {
      "source": 4,
      "target": 0,
      "value": 1
    }, {
      "source": 5,
      "target": 0,
      "value": 1
    }, {
      "source": 6,
      "target": 0,
      "value": 1
    }, {
      "source": 7,
      "target": 0,
      "value": 1
    }, {
      "source": 8,
      "target": 0,
      "value": 2
    }, {
      "source": 9,
      "target": 0,
      "value": 1
    }, {
      "source": 11,
      "target": 10,
      "value": 1
    }, {
      "source": 11,
      "target": 3,
      "value": 3
    }, {
      "source": 11,
      "target": 2,
      "value": 3
    }, {
      "source": 11,
      "target": 0,
      "value": 5
    }, {
      "source": 12,
      "target": 11,
      "value": 1
    }, {
      "source": 13,
      "target": 11,
      "value": 1
    }, {
      "source": 14,
      "target": 11,
      "value": 1
    }, {
      "source": 15,
      "target": 11,
      "value": 1
    }, {
      "source": 17,
      "target": 16,
      "value": 4
    }, {
      "source": 18,
      "target": 16,
      "value": 4
    }, {
      "source": 18,
      "target": 17,
      "value": 4
    }, {
      "source": 19,
      "target": 16,
      "value": 4
    }, {
      "source": 19,
      "target": 17,
      "value": 4
    }, {
      "source": 19,
      "target": 18,
      "value": 4
    }, {
      "source": 20,
      "target": 16,
      "value": 3
    }, {
      "source": 20,
      "target": 17,
      "value": 3
    }, {
      "source": 20,
      "target": 18,
      "value": 3
    }, {
      "source": 20,
      "target": 19,
      "value": 4
    }, {
      "source": 21,
      "target": 16,
      "value": 3
    }, {
      "source": 21,
      "target": 17,
      "value": 3
    }, {
      "source": 21,
      "target": 18,
      "value": 3
    }, {
      "source": 21,
      "target": 19,
      "value": 3
    }, {
      "source": 21,
      "target": 20,
      "value": 5
    }, {
      "source": 22,
      "target": 16,
      "value": 3
    }, {
      "source": 22,
      "target": 17,
      "value": 3
    }, {
      "source": 22,
      "target": 18,
      "value": 3
    }, {
      "source": 22,
      "target": 19,
      "value": 3
    }, {
      "source": 22,
      "target": 20,
      "value": 4
    }, {
      "source": 22,
      "target": 21,
      "value": 4
    }, {
      "source": 23,
      "target": 16,
      "value": 3
    }, {
      "source": 23,
      "target": 17,
      "value": 3
    }, {
      "source": 23,
      "target": 18,
      "value": 3
    }, {
      "source": 23,
      "target": 19,
      "value": 3
    }, {
      "source": 23,
      "target": 20,
      "value": 4
    }, {
      "source": 23,
      "target": 21,
      "value": 4
    }, {
      "source": 23,
      "target": 22,
      "value": 4
    }, {
      "source": 23,
      "target": 12,
      "value": 2
    }, {
      "source": 23,
      "target": 11,
      "value": 9
    }, {
      "source": 24,
      "target": 23,
      "value": 2
    }, {
      "source": 24,
      "target": 11,
      "value": 7
    }, {
      "source": 25,
      "target": 24,
      "value": 13
    }, {
      "source": 25,
      "target": 23,
      "value": 1
    }, {
      "source": 25,
      "target": 11,
      "value": 12
    }, {
      "source": 26,
      "target": 24,
      "value": 4
    }, {
      "source": 26,
      "target": 11,
      "value": 31
    }, {
      "source": 26,
      "target": 16,
      "value": 1
    }, {
      "source": 26,
      "target": 25,
      "value": 1
    }, {
      "source": 27,
      "target": 11,
      "value": 17
    }, {
      "source": 27,
      "target": 23,
      "value": 5
    }, {
      "source": 27,
      "target": 25,
      "value": 5
    }, {
      "source": 27,
      "target": 24,
      "value": 1
    }, {
      "source": 27,
      "target": 26,
      "value": 1
    }, {
      "source": 28,
      "target": 11,
      "value": 8
    }, {
      "source": 28,
      "target": 27,
      "value": 1
    }, {
      "source": 29,
      "target": 23,
      "value": 1
    }, {
      "source": 29,
      "target": 27,
      "value": 1
    }, {
      "source": 29,
      "target": 11,
      "value": 2
    }, {
      "source": 30,
      "target": 23,
      "value": 1
    }, {
      "source": 31,
      "target": 30,
      "value": 2
    }, {
      "source": 31,
      "target": 11,
      "value": 3
    }, {
      "source": 31,
      "target": 23,
      "value": 2
    }, {
      "source": 31,
      "target": 27,
      "value": 1
    }, {
      "source": 32,
      "target": 11,
      "value": 1
    }, {
      "source": 33,
      "target": 11,
      "value": 2
    }, {
      "source": 33,
      "target": 27,
      "value": 1
    }, {
      "source": 34,
      "target": 11,
      "value": 3
    }, {
      "source": 34,
      "target": 29,
      "value": 2
    }, {
      "source": 35,
      "target": 11,
      "value": 3
    }, {
      "source": 35,
      "target": 34,
      "value": 3
    }, {
      "source": 35,
      "target": 29,
      "value": 2
    }, {
      "source": 36,
      "target": 34,
      "value": 2
    }, {
      "source": 36,
      "target": 35,
      "value": 2
    }, {
      "source": 36,
      "target": 11,
      "value": 2
    }, {
      "source": 36,
      "target": 29,
      "value": 1
    }, {
      "source": 37,
      "target": 34,
      "value": 2
    }, {
      "source": 37,
      "target": 35,
      "value": 2
    }, {
      "source": 37,
      "target": 36,
      "value": 2
    }, {
      "source": 37,
      "target": 11,
      "value": 2
    }, {
      "source": 37,
      "target": 29,
      "value": 1
    }, {
      "source": 38,
      "target": 34,
      "value": 2
    }, {
      "source": 38,
      "target": 35,
      "value": 2
    }, {
      "source": 38,
      "target": 36,
      "value": 2
    }, {
      "source": 38,
      "target": 37,
      "value": 2
    }, {
      "source": 38,
      "target": 11,
      "value": 2
    }, {
      "source": 38,
      "target": 29,
      "value": 1
    }, {
      "source": 39,
      "target": 25,
      "value": 1
    }, {
      "source": 40,
      "target": 25,
      "value": 1
    }, {
      "source": 41,
      "target": 24,
      "value": 2
    }, {
      "source": 41,
      "target": 25,
      "value": 3
    }, {
      "source": 42,
      "target": 41,
      "value": 2
    }, {
      "source": 42,
      "target": 25,
      "value": 2
    }, {
      "source": 42,
      "target": 24,
      "value": 1
    }, {
      "source": 43,
      "target": 11,
      "value": 3
    }, {
      "source": 43,
      "target": 26,
      "value": 1
    }, {
      "source": 43,
      "target": 27,
      "value": 1
    }, {
      "source": 44,
      "target": 28,
      "value": 3
    }, {
      "source": 44,
      "target": 11,
      "value": 1
    }, {
      "source": 45,
      "target": 28,
      "value": 2
    }, {
      "source": 47,
      "target": 46,
      "value": 1
    }, {
      "source": 48,
      "target": 47,
      "value": 2
    }, {
      "source": 48,
      "target": 25,
      "value": 1
    }, {
      "source": 48,
      "target": 27,
      "value": 1
    }, {
      "source": 48,
      "target": 11,
      "value": 1
    }, {
      "source": 49,
      "target": 26,
      "value": 3
    }, {
      "source": 49,
      "target": 11,
      "value": 2
    }, {
      "source": 50,
      "target": 49,
      "value": 1
    }, {
      "source": 50,
      "target": 24,
      "value": 1
    }, {
      "source": 51,
      "target": 49,
      "value": 9
    }, {
      "source": 51,
      "target": 26,
      "value": 2
    }, {
      "source": 51,
      "target": 11,
      "value": 2
    }, {
      "source": 52,
      "target": 51,
      "value": 1
    }, {
      "source": 52,
      "target": 39,
      "value": 1
    }, {
      "source": 53,
      "target": 51,
      "value": 1
    }, {
      "source": 54,
      "target": 51,
      "value": 2
    }, {
      "source": 54,
      "target": 49,
      "value": 1
    }, {
      "source": 54,
      "target": 26,
      "value": 1
    }, {
      "source": 55,
      "target": 51,
      "value": 6
    }, {
      "source": 55,
      "target": 49,
      "value": 12
    }, {
      "source": 55,
      "target": 39,
      "value": 1
    }, {
      "source": 55,
      "target": 54,
      "value": 1
    }, {
      "source": 55,
      "target": 26,
      "value": 21
    }, {
      "source": 55,
      "target": 11,
      "value": 19
    }, {
      "source": 55,
      "target": 16,
      "value": 1
    }, {
      "source": 55,
      "target": 25,
      "value": 2
    }, {
      "source": 55,
      "target": 41,
      "value": 5
    }, {
      "source": 55,
      "target": 48,
      "value": 4
    }, {
      "source": 56,
      "target": 49,
      "value": 1
    }, {
      "source": 56,
      "target": 55,
      "value": 1
    }, {
      "source": 57,
      "target": 55,
      "value": 1
    }, {
      "source": 57,
      "target": 41,
      "value": 1
    }, {
      "source": 57,
      "target": 48,
      "value": 1
    }, {
      "source": 58,
      "target": 55,
      "value": 7
    }, {
      "source": 58,
      "target": 48,
      "value": 7
    }, {
      "source": 58,
      "target": 27,
      "value": 6
    }, {
      "source": 58,
      "target": 57,
      "value": 1
    }, {
      "source": 58,
      "target": 11,
      "value": 4
    }, {
      "source": 59,
      "target": 58,
      "value": 15
    }, {
      "source": 59,
      "target": 55,
      "value": 5
    }, {
      "source": 59,
      "target": 48,
      "value": 6
    }, {
      "source": 59,
      "target": 57,
      "value": 2
    }, {
      "source": 60,
      "target": 48,
      "value": 1
    }, {
      "source": 60,
      "target": 58,
      "value": 4
    }, {
      "source": 60,
      "target": 59,
      "value": 2
    }, {
      "source": 61,
      "target": 48,
      "value": 2
    }, {
      "source": 61,
      "target": 58,
      "value": 6
    }, {
      "source": 61,
      "target": 60,
      "value": 2
    }, {
      "source": 61,
      "target": 59,
      "value": 5
    }, {
      "source": 61,
      "target": 57,
      "value": 1
    }, {
      "source": 61,
      "target": 55,
      "value": 1
    }, {
      "source": 62,
      "target": 55,
      "value": 9
    }, {
      "source": 62,
      "target": 58,
      "value": 17
    }, {
      "source": 62,
      "target": 59,
      "value": 13
    }, {
      "source": 62,
      "target": 48,
      "value": 7
    }, {
      "source": 62,
      "target": 57,
      "value": 2
    }, {
      "source": 62,
      "target": 41,
      "value": 1
    }, {
      "source": 62,
      "target": 61,
      "value": 6
    }, {
      "source": 62,
      "target": 60,
      "value": 3
    }, {
      "source": 63,
      "target": 59,
      "value": 5
    }, {
      "source": 63,
      "target": 48,
      "value": 5
    }, {
      "source": 63,
      "target": 62,
      "value": 6
    }, {
      "source": 63,
      "target": 57,
      "value": 2
    }, {
      "source": 63,
      "target": 58,
      "value": 4
    }, {
      "source": 63,
      "target": 61,
      "value": 3
    }, {
      "source": 63,
      "target": 60,
      "value": 2
    }, {
      "source": 63,
      "target": 55,
      "value": 1
    }, {
      "source": 64,
      "target": 55,
      "value": 5
    }, {
      "source": 64,
      "target": 62,
      "value": 12
    }, {
      "source": 64,
      "target": 48,
      "value": 5
    }, {
      "source": 64,
      "target": 63,
      "value": 4
    }, {
      "source": 64,
      "target": 58,
      "value": 10
    }, {
      "source": 64,
      "target": 61,
      "value": 6
    }, {
      "source": 64,
      "target": 60,
      "value": 2
    }, {
      "source": 64,
      "target": 59,
      "value": 9
    }, {
      "source": 64,
      "target": 57,
      "value": 1
    }, {
      "source": 64,
      "target": 11,
      "value": 1
    }, {
      "source": 65,
      "target": 63,
      "value": 5
    }, {
      "source": 65,
      "target": 64,
      "value": 7
    }, {
      "source": 65,
      "target": 48,
      "value": 3
    }, {
      "source": 65,
      "target": 62,
      "value": 5
    }, {
      "source": 65,
      "target": 58,
      "value": 5
    }, {
      "source": 65,
      "target": 61,
      "value": 5
    }, {
      "source": 65,
      "target": 60,
      "value": 2
    }, {
      "source": 65,
      "target": 59,
      "value": 5
    }, {
      "source": 65,
      "target": 57,
      "value": 1
    }, {
      "source": 65,
      "target": 55,
      "value": 2
    }, {
      "source": 66,
      "target": 64,
      "value": 3
    }, {
      "source": 66,
      "target": 58,
      "value": 3
    }, {
      "source": 66,
      "target": 59,
      "value": 1
    }, {
      "source": 66,
      "target": 62,
      "value": 2
    }, {
      "source": 66,
      "target": 65,
      "value": 2
    }, {
      "source": 66,
      "target": 48,
      "value": 1
    }, {
      "source": 66,
      "target": 63,
      "value": 1
    }, {
      "source": 66,
      "target": 61,
      "value": 1
    }, {
      "source": 66,
      "target": 60,
      "value": 1
    }, {
      "source": 67,
      "target": 57,
      "value": 3
    }, {
      "source": 68,
      "target": 25,
      "value": 5
    }, {
      "source": 68,
      "target": 11,
      "value": 1
    }, {
      "source": 68,
      "target": 24,
      "value": 1
    }, {
      "source": 68,
      "target": 27,
      "value": 1
    }, {
      "source": 68,
      "target": 48,
      "value": 1
    }, {
      "source": 68,
      "target": 41,
      "value": 1
    }, {
      "source": 69,
      "target": 25,
      "value": 6
    }, {
      "source": 69,
      "target": 68,
      "value": 6
    }, {
      "source": 69,
      "target": 11,
      "value": 1
    }, {
      "source": 69,
      "target": 24,
      "value": 1
    }, {
      "source": 69,
      "target": 27,
      "value": 2
    }, {
      "source": 69,
      "target": 48,
      "value": 1
    }, {
      "source": 69,
      "target": 41,
      "value": 1
    }, {
      "source": 70,
      "target": 25,
      "value": 4
    }, {
      "source": 70,
      "target": 69,
      "value": 4
    }, {
      "source": 70,
      "target": 68,
      "value": 4
    }, {
      "source": 70,
      "target": 11,
      "value": 1
    }, {
      "source": 70,
      "target": 24,
      "value": 1
    }, {
      "source": 70,
      "target": 27,
      "value": 1
    }, {
      "source": 70,
      "target": 41,
      "value": 1
    }, {
      "source": 70,
      "target": 58,
      "value": 1
    }, {
      "source": 71,
      "target": 27,
      "value": 1
    }, {
      "source": 71,
      "target": 69,
      "value": 2
    }, {
      "source": 71,
      "target": 68,
      "value": 2
    }, {
      "source": 71,
      "target": 70,
      "value": 2
    }, {
      "source": 71,
      "target": 11,
      "value": 1
    }, {
      "source": 71,
      "target": 48,
      "value": 1
    }, {
      "source": 71,
      "target": 41,
      "value": 1
    }, {
      "source": 71,
      "target": 25,
      "value": 1
    }, {
      "source": 72,
      "target": 26,
      "value": 2
    }, {
      "source": 72,
      "target": 27,
      "value": 1
    }, {
      "source": 72,
      "target": 11,
      "value": 1
    }, {
      "source": 73,
      "target": 48,
      "value": 2
    }, {
      "source": 74,
      "target": 48,
      "value": 2
    }, {
      "source": 74,
      "target": 73,
      "value": 3
    }, {
      "source": 75,
      "target": 69,
      "value": 3
    }, {
      "source": 75,
      "target": 68,
      "value": 3
    }, {
      "source": 75,
      "target": 25,
      "value": 3
    }, {
      "source": 75,
      "target": 48,
      "value": 1
    }, {
      "source": 75,
      "target": 41,
      "value": 1
    }, {
      "source": 75,
      "target": 70,
      "value": 1
    }, {
      "source": 75,
      "target": 71,
      "value": 1
    }, {
      "source": 76,
      "target": 64,
      "value": 1
    }, {
      "source": 76,
      "target": 65,
      "value": 1
    }, {
      "source": 76,
      "target": 66,
      "value": 1
    }, {
      "source": 76,
      "target": 63,
      "value": 1
    }, {
      "source": 76,
      "target": 62,
      "value": 1
    }, {
      "source": 76,
      "target": 48,
      "value": 1
    }, {
      "source": 76,
      "target": 58,
      "value": 1
    }]
}